### ISSUE TITLE
Error when using iPad to synchronize MN3 and OB

### ISSUE THREAD

**Issue by MugenLee** [aidenlx/marginnote-companion#12]
hi aidenlx
你好呀，aidenlx

I was very happy when I saw this plug-in, because I was worrying about how to maintain the interoperability of PDF notes between Obsidian on iPad and Obsidian on Win10.
看到这款插件时我非常高兴，因为我正在苦恼iPad的Obsidian如何与Win10的Obsidian保持PDF笔记的互通

I experienced a lot of difficulties in the middle, and I successfully debugged, but I found that the most important TOC could not be synchronized
中间经历了很多困难，我调试成功了，然而我发现最重要的TOC不能同步
![d6114a09b6e985fa287b8a9053a3862](https://user-images.githubusercontent.com/91043731/135938096-60e9eca3-4b4d-465b-bb3a-300cf882cade.jpg)

There are many friends around me who use MarginNote via iPad like me, and use Obsidian (win10)
我身边有不少和我一样通过iPad使用MarginNote的朋友，并且使用着Obsidian（win10）

We all hope that this plug-in can connect them, but we are stuck on this bug
我们都寄望于这个插件能把它们联通起来，然而却卡在了这个BUG上

Please take a look at this BUG, ​​I am eager to solve it, thank you very much
请看看这个BUG，迫切希望能解决它，非常感谢

We are expecting your reply
期待你的回复

**Comment by aidenlx** [comment]
should be fixed in [v0.6.4](https://github.com/aidenlx/marginnote-companion/releases/tag/0.6.4)

**Comment by Meyerclex** [comment]
> 

我下载这个插件时已经是v0.8.3了，但同样在iPad上遇到了这个错误，请问应该怎么办呢？

**Comment by aidenlx** [comment]
你单独开个issue吧，错误发上来 @Meyerclex
