### ISSUE TITLE
obsidian端会导致metadata里的别名跑到正文里。

### ISSUE THREAD

**Issue by xfxme** [aidenlx/marginnote-companion#15]
<img width="636" alt="image" src="https://user-images.githubusercontent.com/76150389/137459685-5ff17e0f-485e-410b-84f6-225b9c131800.png">
已经排查所有插件和主题，只有装了obsidian-bridge会出来这样的情况。不知道它和什么插件冲突还是其他什么的原因就不知道了。关闭bridge就不会出现别名乱跑的现象。
<img width="223" alt="image" src="https://user-images.githubusercontent.com/76150389/137460004-025c940d-fdc3-4b23-8763-666a0cfcfc0d.png">

**Comment by aidenlx** [comment]
具体怎么操作的可以录个屏吗，我看看能不能复现

**Comment by xfxme** [comment]
没有怎么操作呀，只要装了bridge后，凡是装之前有别名的文档都会出现别名跑下面来的情况。装了之后才增加别名的，重启后也会别名跑下面去。

**Comment by Miaoyifei-mz** [comment]
确实会出现这样的情况，打开 Marginnoge companion 插件后输入一级标题，别名会在它下面再次出现，当关闭插件后不会出现这种情况。
