### ISSUE TITLE
目录模式有缺陷

### ISSUE THREAD

**Issue by liang-0131** [aidenlx/marginnote-companion#19]
如图当摘录卡片有标题时内容无法生成，最好添加一个缩进
[![INixZd.png](https://z3.ax1x.com/2021/11/09/INixZd.png)](https://imgtu.com/i/INixZd)

**Comment by aidenlx** [comment]
可以在模板自定义输出的内容：https://github.com/aidenlx/marginnote-companion/wiki/Template-Syntax#summary
