### ISSUE TITLE
能否把「在Obsidian的MN URL在预览模式下显示为MN的图标」这个功能拓展到其它app？

### ISSUE THREAD

**Issue by LoneFireBlossom** [aidenlx/marginnote-companion#24]
我说的MN的图标就是下图这个，一张图就能说清楚的事情用句子表述要老长了……
<img width="607" alt="image" src="https://user-images.githubusercontent.com/50087596/146771252-5df36d4c-9ee4-4b29-ab97-c2abd61dd6a6.png">

现在比如说，我还用devonthink，所以希望devonthink的item link（如 x-devonthink-item://19AFD930-EE85-47E1-93D4-AEC9FDE787BA ）在Obsidian的预览模式下显示为devonthink的图标。
再比如Day One的。
再比如，如果是网页链接，可以显示为一个Safari浏览器的图标。

感觉这个需求可以单独做一个插件了，而且应该挺好做的（就是我不会😂）

**Comment by aidenlx** [comment]
https://github.com/joethei/obsidian-link-favicon

可以蹲一下跟自定义图标的联用：https://github.com/joethei/obsidian-link-favicon/issues/1#issuecomment-993400869
