### ISSUE TITLE
Documentation of Usage

### ISSUE THREAD

**Issue by TobiasKlosek** [aidenlx/marginnote-companion#4]
It would be nice to offer some screenshots on how to use the bridge, to let the people know. :)

**Comment by aidenlx** [comment]
I'm currently occupied and don't have time to write docs yet. And btw, I'm actually curious about where you found this plugin since I haven't officially introduced the plugin to the general public and create PR to the community plugin list. 👀

**Comment by TobiasKlosek** [comment]
Im heavily using Obsidian and MarginNote and was looking for some ways to bridge them. After googling obsidian and marginnote your GitRepo was shown. :D

**Comment by aidenlx** [comment]
User guide is ready and the plugin is now pending review: https://github.com/aidenlx/marginnote-companion/wiki
