### ISSUE TITLE
Image support

### ISSUE THREAD

**Issue by TobiasKlosek** [aidenlx/marginnote-companion#5]
It would be awesome if the Bridge could also copy the image to Obsidian.
Since MarginNote allows to extract areas it would be super nice to enhance the functionality for images.

**Comment by aidenlx** [comment]
Currently, only notes (with excerpt) are supported, not selections due to API restriction, so you need to make selection notes first, then tap on note to get picture imported.

**Comment by TobiasKlosek** [comment]
Sorry but I dont understand the workflow.. might sharing a simple example?

**Comment by aidenlx** [comment]
https://user-images.githubusercontent.com/31102694/133354949-7ab4d0bd-e11b-4ce7-b1bd-bbd54a59956c.mp4

**Comment by TobiasKlosek** [comment]
Thanks but this dont work for me on the iPad. I selected an Image and Inserted the MarginNote-Data via the Command-Palette but nothing happens.

**Comment by aidenlx** [comment]
update to v0.6.1 should fix the issue of notes with pictures not getting imported
