### ISSUE TITLE
Define specific Syntax

### ISSUE THREAD

**Issue by TobiasKlosek** [aidenlx/marginnote-companion#6]
It would help to save time if there were a possibility to define a specific Syntax how the Notes will be copied into Obsidian.
I for example strictly use the "Title" - "Content" Method. By now the title is put into an H2-Heading which is absolutely fine.

Since Im using [admonition-plugin](https://github.com/valentine195/obsidian-admonition) which uses the following Syntax:
```
!!! ad-info
CONTENT
--- admonition
```

It would be super nice to have the possibility to define it that way:
```
!!! ad-info
## H2-Heading of the MarginNote-Note
Here comes the actual content and images for e.g.
--- admonition
```

That would be super helpful and allow users to modify the extracts of MarginNote!

**Comment by aidenlx** [comment]
You can check wiki for [template guide](https://github.com/aidenlx/marginnote-companion/wiki/Templates)
