### ISSUE TITLE
能否实现将笔记导出为纯粹MN格式，实现其他双链笔记也能够直接复制？

### ISSUE THREAD

**Issue by clark874** [aidenlx/marginnote-companion#9]
感谢作者提供的插件，非常实用！

目前在使用中已经实现了将笔记批量导出到obsidian的功能，但发现在obsidian中显示方式不是直接的笔记链接，而是点击图标后跳转到笔记
![image](https://user-images.githubusercontent.com/86122040/133919344-c7a85ef4-dc81-4c65-873e-792813c7bd30.png)
对应的格式是：术语表 [](marginnote3app://note/C908309B-84F4-44D9-9F75-6F7817DE68FD)
我目前还在使用另一个双链笔记，无法识别这样的格式，但我发现如果直接将笔记地址链接到标题，即[术语表](marginnote3app://note/C908309B-84F4-44D9-9F75-6F7817DE68FD)，就可以被识别。
能否提供这样的选项，让mn笔记能够导出到除了obsidian之外的markdown笔记中？

再次感谢作者！

**Comment by aidenlx** [comment]
目前你在设置里可以在笔记模板把`{{Link}}`替换成`[希望显示的文本]({{Link.Url}})`解决

**Comment by clark874** [comment]
> 目前你在设置里可以在笔记模板把`{{Link}}`替换成`[希望显示的文本]({{Link.Url}})`解决
> 
> 其实命令里有一个import meta的功能，可以把标题链接导入到现有笔记的h1和frontmatter的`aliases`字段里去，可以在ob实现类似的功能，但是目前批量导入这方面还不是重点，未来可能会考虑加进来

感谢作者回复，我在设置里试过了：
![image](https://user-images.githubusercontent.com/86122040/134030441-b6cf834b-8242-485b-8df6-1ce75ee26679.png)
不成功，我用预览模板：
![image](https://user-images.githubusercontent.com/86122040/134030615-790bc6d8-43ba-4f30-bed1-d828829cd2d8.png)
请问如何解决？谢谢！

**Comment by aidenlx** [comment]
不好意思搞错了😂你TOC模板里也可以加上这个，预览功能的话需要选择同类型的（比如TOC就需要先开TOC模式选中后选择TOC模板的预览）
